### ISSUE TITLE
Undecipherable crash

### ISSUE THREAD

**Issue by sadris** [INpureProjects/INpureCore#18]
I'm getting the following error on world start. I'm using INpureCore-[1.7.10]1.0.0B9-65 from your maven repo.

I do not have Microblocks installed, and it occurs even with the entire INpureProjects directory deleted.
```
java.lang.NullPointerException
	at info.inpureprojects.core.Scripting.ScriptingCore.initialize(ScriptingCore.java:90)
	at info.inpureprojects.core.NEI.gtfoMicroblocks.NEIINpureConfig.runCommands(NEIINpureConfig.java:143)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_900_NEIINpureConfig_runCommands_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
...
```

**Comment by denoflionsx** [comment]
Are you using OpenJDK? This is a known issue with non-Sun JDKs.

**Comment by sadris** [comment]
Yeah I just now suspected that, works fine on Sun's. Seems to be an issue with OpenJDK 7 not including Rhino. Allegedly OpenJDK 8 and 9 do, though.

**Comment by SvEgiiVEteR** [comment]
how to solve a problem?
How to install Rhino, without changing the java?
