### ISSUE TITLE
Script error with AE2 facades

### ISSUE THREAD

**Issue by Breadabix** [INpureProjects/INpureCore#26]
I dont know anything about how the scripts work, so any help appreciated.

https://pastebin.com/jntw9cBZ

**Comment by Breadabix** [comment]
IDK what is going on, I am no longer getting a script error, but the script isnt working :/

if (FML.isModLoaded("appliedenergistics2") && AE2_enabled) {
    NEI.override(AE2.getFacadeItem(), [java.random(AE2.getNumberOfTypes())]);
}

**Comment by Breadabix** [comment]
And doing the command to reload scrips gives me this:

java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Unknown Source)
	at jdk.nashorn.internal.runtime.Source$RawData.<init>(Source.java:169)
	at jdk.nashorn.internal.runtime.Source$RawData.<init>(Source.java:158)
	at jdk.nashorn.internal.runtime.Source.sourceFor(Source.java:429)
	at jdk.nashorn.internal.runtime.Source.sourceFor(Source.java:440)
	at jdk.nashorn.api.scripting.NashornScriptEngine.makeSource(NashornScriptEngine.java:226)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(Unknown Source)
	at info.inpureprojects.core.Scripting.ScriptingCore.loadStream(ScriptingCore.java:119)
	at info.inpureprojects.core.Scripting.ScriptingCore.loadFile(ScriptingCore.java:108)
	at info.inpureprojects.core.Scripting.ScriptingCore.loadPackagesFromDir(ScriptingCore.java:187)
	at info.inpureprojects.core.NEI.gtfoMicroblocks.NEIINpureConfig.runCommands(NEIINpureConfig.java:158)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1910_NEIINpureConfig_runCommands_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:325)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1587)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
