### ISSUE TITLE
java.lang.NoSuchFieldError: preLoaderEvents

### ISSUE THREAD

**Issue by KeepOnDigging** [INpureProjects/INpureCore#8]
Error with INpureCore-[1.7.10]1.0.0B8-49.jar :

[09:07:14] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:289]: Failed to start Minecraft:
[09:07:14] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.reflect.InvocationTargetException
[09:07:14] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:07:14] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[09:07:14] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:07:14] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:606)
[09:07:14] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
[09:07:14] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
[09:07:14] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:165)
[09:07:14] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.multimc.EntryPoint.main(EntryPoint.java:54)
[09:07:14] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.NoSuchFieldError: preLoaderEvents
[09:07:14] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at info.inpureprojects.CreeperCollateral.Preloader.CCPreloader.injectData(CCPreloader.java:43)
[09:07:14] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:112)
[09:07:14] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[09:07:14] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Massively huge log here: http://pastebin.com/1RKQY7mn

**Comment by denoflionsx** [comment]
Interesting. I need to work on CC anyways.
